from datetime import datetime, timezone
from pathlib import Path
import json, csv, io, uuid
from . import models
from .repositories import one_or_404, audit

class StubEngine:
    """Offline engine with the same useful output shape as ai-engine."""
    def analyze(self, request):
        score = max(0, 100 - min(70, len(request.readings) * 2) - (20 if request.manual_condition else 0))
        priority = "critical" if score < 40 else "high" if score < 65 else "medium" if score < 85 else "low"
        return {"health_score": score, "health_summary": f"Health score {score}/100", "anomalies": [], "defects": [], "root_causes": [{"cause": "Condition requires inspection" if request.manual_condition else "No significant signal", "confidence": 0.55, "evidence": [request.manual_condition] if request.manual_condition else []}], "recommendation": "Inspect and schedule preventive maintenance" if priority != "low" else "Continue monitoring", "priority": priority, "recommended_window": "Next available maintenance window", "explanation": "Generated by offline Starter engine stub", "blockers": [], "work_order": {"title": "Inspect asset", "steps": ["Inspect machine condition", "Verify readings"], "parts": [], "est_duration_h": 2, "required_skills": ["maintenance"], "safety_notes": ["Apply lockout/tagout"]}, "tier": request.tier.value, "model": "offline-stub", "sources": []}
    mode = "offline_stub"
    def ask(self, request, question): return f"Offline Starter answer for '{question}': review the asset condition and applicable SOP."

class EngineUnavailable(RuntimeError):
    code = "AI_ENGINE_UNAVAILABLE"

def engine_factory(settings):
    if settings.ai_engine_enabled:
        try:
            from src import MaintenanceEngine
            return MaintenanceEngine()
        except Exception as exc:
            raise EngineUnavailable("AI engine enabled tetapi gagal di-load atau dikonfigurasi") from exc
    if settings.app_env in {"demo", "local", "test"}:
        return StubEngine()
    raise EngineUnavailable("AI engine disabled; offline stub hanya tersedia pada demo mode")

def engine_request(asset, readings, history, business, condition, tier):
    try:
        from src import AnalysisRequest, Asset, BusinessContext, MaintenanceRecord, SensorReading, Tier
        return AnalysisRequest(tier=Tier(tier), asset=Asset(id=asset.id, name=asset.name, type=asset.asset_type, criticality=asset.criticality, specs=asset.specs_json), readings=[SensorReading(tag=x.tag, value=x.value, unit=x.unit, recorded_at=x.recorded_at) for x in readings], manual_condition=condition, history=[MaintenanceRecord(asset_id=x.asset_id, performed_at=x.performed_at, action=x.action, findings=x.findings, parts_used=x.parts_used_json) for x in history], business=BusinessContext(**business))
    except (ImportError, ModuleNotFoundError):
        class TierValue: value = tier
        return type("Request", (), {"tier": TierValue(), "asset": asset, "readings": readings, "history": history, "business": business, "manual_condition": condition})()

def run_analysis(db, asset, payload, identity, request_id, settings):
    readings = list(db.scalars(__import__('sqlalchemy').select(models.Reading).where(models.Reading.asset_id == asset.id).order_by(models.Reading.recorded_at.desc()).limit(200)))
    history = list(db.scalars(__import__('sqlalchemy').select(models.MaintenanceRecord).where(models.MaintenanceRecord.asset_id == asset.id).order_by(models.MaintenanceRecord.performed_at.desc()).limit(20)))
    context = db.get(models.BusinessContext, asset.id)
    business = {"production_schedule": context.production_schedule if context else None, "spareparts": context.spareparts_json if context else [], "sparepart_eta": context.sparepart_eta if context else None, "technicians_available": context.technicians_available if context else None, "operator_report": context.operator_report if context else None}
    request = engine_request(asset, readings, history, business, payload.manual_condition or (context.operator_report if context else None), payload.tier)
    started = datetime.now(timezone.utc)
    snapshot = {"asset": {"id": asset.id, "name": asset.name, "type": asset.asset_type, "criticality": asset.criticality, "location": asset.location, "specs": asset.specs_json}, "readings": [{"id": x.id, "tag": x.tag, "value": x.value, "unit": x.unit, "recorded_at": x.recorded_at.isoformat(), "source": x.source, "external_id": x.external_id} for x in readings], "history": [{"id": x.id, "performed_at": x.performed_at.isoformat(), "action": x.action, "findings": x.findings, "parts_used": x.parts_used_json} for x in history], "condition": payload.manual_condition, "business": business, "tier": payload.tier, "trigger": payload.trigger, "engine_mode": "stub"}
    run = models.AnalysisRun(factory_id=identity.factory_id, asset_id=asset.id, tier=payload.tier, trigger=payload.trigger, status="running", started_at=started, request_snapshot_json=snapshot)
    db.add(run); db.flush()
    try:
        engine = engine_factory(settings)
        result = engine.analyze(request)
        if hasattr(result, "model_dump"): result = result.model_dump(mode="json")
        run.status = "succeeded"; run.result_json = result; run.health_score = result.get("health_score"); run.priority = result.get("priority"); run.model = result.get("model"); run.engine_mode = getattr(engine, "mode", "ai_engine"); run.finished_at = datetime.now(timezone.utc)
        audit(db, identity, request_id, "analysis.completed", "analysis", run.id, after={"status": run.status, "priority": run.priority})
    except EngineUnavailable as exc:
        run.status = "failed"; run.error_code = exc.code; run.error_message = str(exc); run.engine_mode = "unavailable"; run.finished_at = datetime.now(timezone.utc)
    except Exception:
        run.status = "failed"; run.error_code = "ANALYSIS_FAILED"; run.error_message = "analysis engine gagal memproses request"; run.engine_mode = "error"; run.finished_at = datetime.now(timezone.utc)
    run.duration_ms = max(0, int((run.finished_at - started).total_seconds() * 1000))
    db.commit(); db.refresh(run)
    return run

TRANSITIONS = {"draft": {"pending_approval", "cancelled"}, "pending_approval": {"approved", "rejected", "cancelled"}, "approved": {"scheduled", "cancelled"}, "scheduled": {"in_progress", "cancelled"}, "in_progress": {"blocked", "completed", "cancelled"}, "blocked": {"in_progress", "cancelled"}, "completed": set(), "cancelled": set(), "rejected": set()}
def transition(db, order, target, identity, request_id):
    if target not in TRANSITIONS.get(order.status, set()): raise ValueError(f"invalid_transition:{order.status}->{target}")
    before = {"status": order.status}; order.status = target
    audit(db, identity, request_id, "work_order.status_changed", "work_order", order.id, before, {"status": target})
    db.commit(); db.refresh(order); return order
